stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  image: imbios/bun-node:latest-24-debian
  only:
    - main
    - staging
  allow_failure: true
  script:
    - bun i --frozen-lockfile --cache-dir .bun --prefer-offline
    - bun run lint:ec
    - bun run lint:es
  cache:
    - key:
        files:
          - bun.lock
      paths:
        - .bun/

build:
  stage: build
  image: oven/bun:1
  only:
    - main
    - staging
  script:
    - bun i --frozen-lockfile --cache-dir .bun --prefer-offline
    - bun run build
    - bun run build:gutenberg
  cache:
    - key:
        files:
          - bun.lock
      paths:
        - .bun/
      policy: pull
  artifacts:
    paths:
      - .deploy-include
      - public/wp-content/themes/wordpress-boilerplate/assets/
      - public/wp-content/mu-plugins/wordpress-boilerplate/modules/gutenberg/blocks/assets/

deploy:
  stage: deploy
  image:
    name: ghcr.io/dotsunited/deploy:v0
  variables:
    DEPLOY_LOCAL_PATH: ./public
    GIT_DEPTH: "0"
  resource_group: deploy-$CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables:
        DEPLOY_ENV: production
    - if: '$CI_COMMIT_REF_NAME == "staging"'
      variables:
        DEPLOY_ENV: staging
  environment:
    name: $DEPLOY_ENV
  script:
    - deploy
