name: 🚀 Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        protocol: ${{ vars.FTP_PROTOCOL }}
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ vars.FTP_PATH }}
        local-dir: ${{ vars.LOCAL_PATH }}
